# File: azure-pipelines.yml

name: $(Build.SourceBranchName)_$(Date:yyyymmdd).$(Rev:.r)

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
  paths:
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: FakeJob
  pool:
  - vmImage: 'Ubuntu-16.04'
  steps:
    - bash: echo $(System.HostType)
