# File: azure-pipelines.yml
# Main AZP YAML file

name: $(Build.SourceBranchName)_$(Date:yyyymmdd).$(Rev:.r)

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
  paths:
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: TestUnitGateway
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.11' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(system.defaultWorkingDirectory)/gateway/gateway' # Path to the module's code
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: infrastructure/azp/template/step/goSetupDirectory.yml
      parameters:
        GOBIN: $(GOBIN)
        GOROOT: $(GOROOT)
        GOPATH: $(GOPATH)
    - bash: |
        git status
        pwd
        ls -ah
        go get -v -t -d ./...
        go test -tags=unit ./...
      workingDirectory: '$(modulePath)'
      displayName: 'Get dependencies, then run unit tests'
