# File: azure-pipelines.yml
# Main AZP YAML file

name: $(Build.BuildId)

variables:
  - group: Common
  - name: GatewayVersion
    value: '0.1.1'
  - name: MssqlVersion
    value: '0.3.2'
  

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
  paths:
    include:
      - infrastructure/azp/*
      - '*'
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: 'TestGatewayUnitTests'
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.11' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(system.defaultWorkingDirectory)/gateway/gateway' # Path to the module's code
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: 'infrastructure/azp/template/step/goSetupDirectory.yml'
      parameters:
        GOBIN: $(GOBIN)
        GOROOT: $(GOROOT)
        GOPATH: $(GOPATH)
    - bash: go get -v -d ./...
      workingDirectory: '$(modulePath)'
      displayName: 'Get dependencies'
    - bash: go test -tags=unit ./...
      workingDirectory: '$(modulePath)'
      displayName: 'Run unit tests'
- job: 'BuildGatewayImage'
  variables:
  - name: GatewayImageQualified
    value: '$(DockerHubOrg)/$(GatewayImageName)'
  - name: GatewayImageTagVersion
    value: '$(GatewayImageQualified):$(GatewayVersion)'
  - name: GatewayImageTagVersionBuildId
    value: '$(GatewayImageTagVersion)-build-$(Build.BuildId)'
  - name: GatewayImageTagVersionBuildIdBranch
    value: '$(GatewayImageTagVersionBuildId)-branch-$(Build.SourceBranchName)'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: 'TestGatewayUnitTests'
  condition: succeeded()
  steps:
  - template: 'infrastructure/azp/template/step/dockerStandardBuildTagPush.yml'
    parameters:
      dockerFile: '$(system.defaultWorkingDirectory)/gateway/Dockerfile'
      qualifiedImageName: $(GatewayImageQualified)
      versionBuildIdBranchTag: $(GatewayImageTagVersionBuildIdBranch)
      versionTag: $(GatewayImageTagVersion)
      versionBuildIdTag: $(GatewayImageTagVersionBuildId)
- job: 'BuildMssqlImage'
  variables:
  - name: MssqlImageQualified
    value: '$(DockerHubOrg)/$(MssqlImageName)'
  - name: MssqlImageTagVersion
    value: '$(MssqlImageQualified):$(MssqlVersion)'
  - name: MssqlImageTagVersionBuildId
    value: '$(MssqlImageTagVersion)-build-$(Build.BuildId)'
  - name: MssqlImageTagVersionBuildIdBranch
    value: '$(MssqlImageTagVersionBuildId)-branch-$(Build.SourceBranchName)'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: 'infrastructure/azp/template/step/dockerStandardBuildTagPush.yml'
    parameters:
      dockerFile: '$(system.defaultWorkingDirectory)/database/mssql/Dockerfile'
      qualifiedImageName: $(MssqlImageQualified)
      versionBuildIdBranchTag: $(MssqlImageTagVersionBuildIdBranch)
      versionTag: $(MssqlImageTagVersion)
      versionBuildIdTag: $(MssqlImageTagVersionBuildId)
