# File: azure-pipelines.yml
# Main AZP YAML file

name: $(Build.SourceBranchName).$(Date:yyyymmdd)$(Rev:.r)

variables:
  - name: GatewayVersion
    value: '0.1.1'
  - name: MssqlVersion
    value: '0.3.2'

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
  paths:
    include:
      - infrastructure/azp/*
      - '*'
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: 'TestGatewayUnitTests'
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.11' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(system.defaultWorkingDirectory)/gateway/gateway' # Path to the module's code
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: infrastructure/azp/template/step/goSetupDirectory.yml
      parameters:
        GOBIN: $(GOBIN)
        GOROOT: $(GOROOT)
        GOPATH: $(GOPATH)
    - bash: go get -v -d ./...
      workingDirectory: '$(modulePath)'
      displayName: 'Get dependencies'
    - bash: go test -tags=unit ./...
      workingDirectory: '$(modulePath)'
      displayName: 'Run unit tests'
- job: 'BuildGatewayImage'
  variables:
  - group: Common
  - name: GatewayImageQualified
    value: '$(DockerHubOrg)/$(GatewayImageName)'
  - name: GatewayImageTagVersion
    value: $(GatewayImageQualified):$(GatewayVersion)
  - name: GatewayImageTagBuildId
    value: $(GatewayImageQualified):$(Build.BuildId)
  - name: GatewayImageTagVersionBuildId
    value: $(GatewayImageQualified):$(GatewayVersion)-$(Build.BuildId)
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: 'TestGatewayUnitTests'
  condition: succeeded()
  steps:
  - task: Docker@1
    displayName: 'Build image'
    inputs:
      command: Build an image
      dockerFile: '$(system.defaultWorkingDirectory)/gateway/Dockerfile'
      imageName: $(GatewayImageQualified)
      qualifyImageName: false
  - task: Docker@1
    displayName: 'Add tags'
    inputs:
      command: Tag image
      imageName: $(GatewayImageQualified)
      qualifyImageName: false
      arguments: |
        $(GatewayImageTagVersion)
        $(GatewayImageTagBuildId)
        $(GatewayImageTagVersionBuildId)
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: uwthalesiansDockerHubConnection
  - task: Docker@1
    displayName: Push Version Tag
    inputs:
      command: Push an image
      imageName: $(GatewayImageTagVersion)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push BuildId Tag
    inputs:
      command: Push an image
      imageName: $(GatewayImageTagBuildId)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version BuildId Tag
    inputs:
      command: Push an image
      imageName: $(GatewayImageTagVersionBuildId)
      qualifyImageName: false
- job: 'BuildMssqlImage'
  variables:
  - group: Common
  - name: MssqlImageQualified
    value: '$(DockerHubOrg)/$(MssqlImageName)'
  - name: MssqlImageTagVersion
    value: $(MssqlImageQualified):$(MssqlVersion)
  - name: MssqlImageTagBuildId
    value: $(MssqlImageQualified):$(Build.BuildId)
  - name: MssqlImageTagVersionBuildId
    value: $(MssqlImageQualified):$(MssqlVersion)-$(Build.BuildId)
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: Docker@1
    displayName: 'Build image'
    inputs:
      command: Build an image
      dockerFile: '$(system.defaultWorkingDirectory)/database/mssql/Dockerfile'
      imageName: $(MssqlImageQualified)
      qualifyImageName: false
  - task: Docker@1
    displayName: 'Add tags'
    inputs:
      command: Tag image
      imageName: $(MssqlImageQualified)
      qualifyImageName: false
      arguments: |
        $(MssqlImageTagVersion)
        $(MssqlImageTagBuildId)
        $(MssqlImageTagVersionBuildId)
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: uwthalesiansDockerHubConnection
  - task: Docker@1
    displayName: Push Version Tag
    inputs:
      command: Push an image
      imageName: $(MssqlImageTagVersion)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push BuildId Tag
    inputs:
      command: Push an image
      imageName: $(MssqlImageTagBuildId)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version BuildId Tag
    inputs:
      command: Push an image
      imageName: $(MssqlImageTagVersionBuildId)
      qualifyImageName: false
