openapi: 3.0.2
info:
  version: 0.0.1
  title: Gateway Service API
  description: This document describes the APIs that are provided directly by the Gateway service of the Perceptia application. All other APIs in the Perceptia application are handled by seperate services which the Gateway passes along.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - description: Perceptia Production API Server
    url: 'https://api.perceptia.info'
  - description: Perceptia Development API Server
    url: 'https://api.dev.perceptia.info'
  - description: Localhost Development API Server
    url: 'https://localhost:4443'
paths:
  /v1/testHealth:
    get:
      summary: Gets the current health of the api gateway
      description: This path is not intended for production use. This is only for testing purposes and will be removed at some point.
      operationId: getGatewayHealth
      tags:
        - health
      responses:
        '200':
          description: Plain text noting gateway is okay
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Plain text noting service is down
          content:
            text/plain:
              schema:
                type: string