# File: dockerStandardTagPush.yml
# Standard tag and push process

parameters:
  qualifiedImageName: '' # dockerhuborg/imagename
  versionMajor: '' # major '1'
  versionMinor: '' # minor '1'
  versionPatch: '' # patch '1'
  buildId: '' # buildNumber '127'
  branch: '' # branchName 'develop'
  tagProduction: false
variables:
  versionBuildIdBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}.${{ parameters.versionPatch }}-build-${{ parameters.buildId }}-branch-${{ parameters.branch }}
  versionMajorBuildBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}-build-${{ parameters.buildId }}-branch-${{ parameters.branch }}
  versionMinorBuildBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}-build-${{ parameters.buildId }}-branch-${{ parameters.branch }}
  versionLatestBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}.${{ parameters.versionPatch }}-build-latest-branch-${{ parameters.branch }}
  versionMajorLatestBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}-build-latest-branch-${{ parameters.branch }}
  versionMinorLatestBranchTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}-build-latest-branch-${{ parameters.branch }}
  versionTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}.${{ parameters.versionPatch }}
  versionMajorTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}
  versionMinorTag: ${{ parameters.qualifiedImageName }}:${{ parameters.versionMajor }}.${{ parameters.versionMinor }}
  versionLatestTag: ${{ parameters.qualifiedImageName }}:latest
steps:
  - task: Docker@1
    displayName: 'Add branch specific tags'
    inputs:
      command: Tag image
      imageName: ${{ parameters.qualifiedImageName }}
      qualifyImageName: false
      arguments: |
        $(versionBuildIdBranchTag)
        $(versionMajorBuildBranchTag)
        $(versionMinorBuildBranchTag)
        $(versionLatestBranchTag)
        $(versionMajorLatestBranchTag)
        $(versionMinorLatestBranchTag)
  - task: Docker@1
    displayName: 'Add production tags'
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Tag image
      imageName: ${{ parameters.qualifiedImageName }}
      qualifyImageName: false
      arguments: |
        $(versionTag)
        $(versionMajorTag)
        $(versionMinorTag)
        $(versionLatestTag)
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: uwthalesiansDockerHubConnection
  - task: Docker@1
    displayName: Push Version BuildId Branch Tag
    inputs:
      command: Push an image
      imageName: $(versionBuildIdBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push VersionMajor BuildId Branch Tag
    inputs:
      command: Push an image
      imageName: $(versionMajorBuildBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push VersionMinor BuildId Branch Tag
    inputs:
      command: Push an image
      imageName:  $(versionMinorBuildBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version Latest Branch Tag
    inputs:
      command: Push an image
      imageName: $(versionLatestBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push VersionMajor Latest Branch Tag
    inputs:
      command: Push an image
      imageName: $(versionMajorLatestBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push VersionMinor Latest Branch Tag
    inputs:
      command: Push an image
      imageName: $(versionMinorLatestBranchTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Production Version Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: $(versionTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Production Version Major Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: $(versionMajorTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Production Version Minor Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: $(versionMinorTag)
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Production Version Latest Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: $(versionLatestTag)
      qualifyImageName: false