# File: dockerStandardTagPush.yml
# Standard tag and push process

parameters:
  qualifiedImageName: ''
  versionLatestBranchTag: ''
  versionBuildIdBranchTag: ''
  versionTag: ''
  versionBuildIdTag: ''
  tagProduction: false

steps:
  - task: Docker@1
    displayName: 'Add branch specific tags'
    inputs:
      command: Tag image
      imageName: ${{ parameters.qualifiedImageName }}
      qualifyImageName: false
      arguments: |
        ${{ parameters.versionBuildIdBranchTag }}
        ${{ parameters.versionLatestBranchTag }}
  - task: Docker@1
    displayName: 'Add production tags'
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Tag image
      imageName: ${{ parameters.qualifiedImageName }}
      qualifyImageName: false
      arguments: |
        ${{ parameters.versionTag }}
        ${{ parameters.versionBuildIdTag }}
  - task: Docker@1
    displayName: Login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: uwthalesiansDockerHubConnection
  - task: Docker@1
    displayName: Push Version BuildId Branch Tag
    inputs:
      command: Push an image
      imageName: ${{ parameters.versionBuildIdBranchTag }}
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version Latest Branch Tag
    inputs:
      command: Push an image
      imageName: ${{ parameters.versionLatestBranchTag }}
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: ${{ parameters.versionTag }}
      qualifyImageName: false
  - task: Docker@1
    displayName: Push Version BuildId Tag
    condition: ${{ parameters.tagProduction }}
    inputs:
      command: Push an image
      imageName: ${{ parameters.versionBuildIdTag }}
      qualifyImageName: false