apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    label.perceptia.info/name: gateway
    label.perceptia.info/instance: gateway-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: frontend
    label.perceptia.info/part-of: perceptia-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        label.perceptia.info/name: gateway
        label.perceptia.info/instance: gateway-1
        label.perceptia.info/version: "1.0.0"
        label.perceptia.info/managed-by: kubectl
        label.perceptia.info/component: server
        label.perceptia.info/type: frontend
        label.perceptia.info/part-of: perceptia-api
    spec:
      containers:
      - name: gateway
        image: uwthalesians/gateway:1-build-455-branch-develop
        ports:
        - name: https
          containerPort: 443
        env:
          - name: GATEWAY_TLSCERTPATH
            value: "/encrypt/tls.crt"
          - name: GATEWAY_TLSKEYPATH
            value: "/encrypt/tls.key"
          - name: AQREST_HOSTNAME
            value: "aqrest"
          - name: AQREST_PORT
            value: "80"
          - name: GATEWAY_SESSION_KEY
            valueFrom:
              secretKeyRef:
                name: gateway
                key: session-key
          - name: GATEWAY_API_PORT
            valueFrom:
              secretKeyRef:
                name: gateway
                key: api-port
          - name: GATEWAY_API_SCHEME
            valueFrom:
              secretKeyRef:
                name: gateway
                key: api-scheme
          - name: GATEWAY_API_HOST
            valueFrom:
              secretKeyRef:
                name: gateway
                key: api-host
          - name: MSSQL_DATABASE
            value: "Perceptia"
          - name: MSSQL_HOST
            value: "mssql"
          - name: MSSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: gateway-sp-password
          - name: MSSQL_PORT
            value: "1433"
          - name: MSSQL_SCHEME
            value: "sqlserver"
          - name: MSSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mssql
                key: gateway-sp-username
          - name: REDIS_ADDRESS
            value: "redis:6379"
        volumeMounts:
          - name: "encrypt"
            mountPath: "/encrypt"
            readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
      volumes:
        - name: "encrypt"
          secret:
            secretName: api-tls  
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    label.perceptia.info/name: redis
    label.perceptia.info/instance: redis-1
    label.perceptia.info/version: "5.0.4"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/type: backend
    label.perceptia.info/sub-of: gateway
spec:
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    label.perceptia.info/name: redis
    label.perceptia.info/instance: redis-1
    label.perceptia.info/version: "5.0.4"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: gateway
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.4-alpine
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis-vol
          mountPath: /data
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    label.perceptia.info/name: mssql
    label.perceptia.info/instance: mssql-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: gateway
spec:
  ports:
  - name: mssql
    protocol: TCP
    port: 1433
    targetPort: mssql
  selector:
    app: mssql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    app: mssql
    label.perceptia.info/name: mssql
    label.perceptia.info/instance: mssql-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: gateway
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: "mssql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: uwthalesians/mssql:1-build-455-branch-develop
        ports:
        - name: mssql
          containerPort: 1433
        env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: sa-password
          - name: GATEWAY_SP_USERNAME
            valueFrom:
              secretKeyRef:
                name: mssql
                key: gateway-sp-username
          - name: GATEWAY_SP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: gateway-sp-password
          - name: ACCEPT_EULA
            value: "Y"
          - name: SKIP_SETUP_IF_EXISTS
            value: "Y"
        volumeMounts:
        - name: mssql-vol
          mountPath: /var/opt/mssql
      volumes:
        - name: mssql-vol
          persistentVolumeClaim:
            claimName: mssql-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: aqrest
  labels:
    label.perceptia.info/name: aqrest
    label.perceptia.info/instance: aqrest-1
    label.perceptia.info/version: "1.1.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
spec:
  selector:
    app: aqrest
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqrest-deployment
  labels:
    label.perceptia.info/name: aqrest
    label.perceptia.info/instance: aqrest-1
    label.perceptia.info/version: "1.1.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqrest
  template:
    metadata:
      labels:
        app: aqrest
        label.perceptia.info/name: aqrest
        label.perceptia.info/instance: aqrest-1
        label.perceptia.info/version: "1.1.0"
        label.perceptia.info/managed-by: kubectl
        label.perceptia.info/component: server
        label.perceptia.info/type: backend
        label.perceptia.info/part-of: perceptia-api
    spec:
      containers:
      - name: aqrest
        image: uwthalesians/aqrest:1.1.0-build-455-branch-develop
        ports:
        - name: http
          containerPort: 80
        env:
          - name: user_pass
            valueFrom:
              secretKeyRef:
                name: aqmysql
                key: user-password
          - name: google_api_key
            valueFrom:
              secretKeyRef:
                name: aqrest
                key: google-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: aqmysql
  labels:
    label.perceptia.info/name: aqmysql
    label.perceptia.info/instance: aqmysql-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: aqrest
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: mysql
  selector:
    app: aqmysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aqmysql
  labels:
    app: aqmysql
    label.perceptia.info/name: aqmysql
    label.perceptia.info/instance: aqmysql-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: database
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: aqrest
spec:
  selector:
    matchLabels:
      app: aqmysql
  serviceName: "aqmysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: aqmysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: aqmysql
        image: uwthalesians/aqmysql:1.0.0-build-455-branch-develop
        ports:
        - name: mysql
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aqmysql
                key: root-password
          - name: user_pass
            valueFrom:
              secretKeyRef:
                name: aqmysql
                key: user-password
        volumeMounts:
        - name: aqmysql-vol
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: 2Gi
      volumes:
        - name: aqmysql-vol
          persistentVolumeClaim:
            claimName: aqmysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aqsolr
  labels:
    label.perceptia.info/name: aqsolr
    label.perceptia.info/instance: aqsolr-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: aqrest
spec:
  ports:
  - name: solr
    protocol: TCP
    port: 8983
    targetPort: solr
  selector:
    app: aqsolr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqsolr-deployment
  labels:
    label.perceptia.info/name: aqsolr
    label.perceptia.info/instance: aqsolr-1
    label.perceptia.info/version: "1.0.0"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: backend
    label.perceptia.info/part-of: perceptia-api
    label.perceptia.info/sub-of: aqrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqsolr
  template:
    metadata:
      labels:
        app: aqsolr
        label.perceptia.info/name: aqsolr
        label.perceptia.info/instance: aqsolr-1
        label.perceptia.info/version: "1.0.0"
        label.perceptia.info/managed-by: kubectl
        label.perceptia.info/component: server
        label.perceptia.info/type: backend
        label.perceptia.info/part-of: perceptia-api
        label.perceptia.info/sub-of: aqrest
    spec:
      containers:
      - name: aqsolr
        image: uwthalesians/aqsolr:1.0.0-build-455-branch-develop
        command: 
          - "solr-precreate"
        args:
          -  stream 
          - /opt/solr/server/solr/configsets/stream
        ports:
        - name: solr
          containerPort: 8983
          